### ISSUE TITLE
Failure with Qt5

### ISSUE THREAD

**Issue by anntzer** [joferkington/mpldatacursor#50]
As of matplotlib 1.5.1 / PyQt5 (Arch Linux standard packages), the first example in the README doesn't work for me.
```
$ MPLBACKEND=qt5agg python /tmp/test.py # copypasted from the README
Exception ignored in: <bound method TimerQT.__del__ of <matplotlib.backends.backend_qt5.TimerQT object at 0x7fe34bd8f048>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 201, in __del__
    self._timer.timeout.disconnect(self._on_timer)
TypeError: 'method' object is not connected
```

**Comment by joferkington** [comment]
Thanks for the bug report!  

Looks like this is a bug in timers in the matplotlib qt5 backend.  (Timers don't get a lot of testing.)  I'll add a workaround to `mpldatacursor` and send a fix upstream as soon as I can get a qt5 backend up and running.

**Comment by joferkington** [comment]
I haven't been able to reproduce this so far using the qt5agg backend on python2.7 and python3.4.  I'll try to get a python3.5 build up and running soon to test with as well.

**Comment by pauljmorrison** [comment]
I think I'm having a related issue. I dont have much experience yet but I'd love to help out debugging & testing. 

I'm not experiencing any errors, just a lack of datacursors but only on scatters (line cursors work just fine). From the examples, `python basic.py` works just fine but `python scatter_example.py` produces no cursors and no errors in the console.

I'm using Anaconda 2.5 (Python 3.5.1, mpl 1.5.1, qt 4.8.7 [i think]).

**Comment by joferkington** [comment]
As it turns out, this is Python 3.5 specific.  I'm not quite sure why, but timers on both the Qt4 and Qt5 backends are broken.  I'll try to dig deeper and send a fix upstream, but in the meantime, 20ccce1da3723ccb5f89e52cc86985d9d5eeb515 should provide a workaround.

If either of you has a chance in the near future, would you mind installing from github and double-checking that this works for you?

Thanks again for the bug reports!!

**Comment by anntzer** [comment]
Thanks for the fix.
- You probably meant a version test such as `three_five = sys.version_info[:2] == (3, 5)` (as it is your check is broken, `sys.version` is a string).
- `HighlightingDataCursor` is still broken.
The rest looks good.

**Comment by joferkington** [comment]
@anntzer - Thanks! Right! That was a typo on my part (meant to put `sys.version_info.major` instead of `sys.version.major`), but regardless, `sys.version_info[:2]` is a far better way.  I feel rather embarrassed. This is why I shouldn't work on projects when I'm exhausted...

I'll fix `HighlightingDataCursor` when I get back tonight.  Something rather strange (and also 3.5-specific) is happening there.

Thanks again!

**Comment by pauljmorrison** [comment]
@joferkington thanks for the quick responses! i re-installed from github and still experience the lack of cursors with the `scatter_example.py`. However, i think this might be matplotlib related since downgrading matplotlib back to 1.4.3 from 1.5.1 allows `scatter_example.py` to produce the expected tooltip. 

Thoughts?

**Comment by pauljmorrison** [comment]
Also, i get this `FutureWarning` with this downgraded matplotlib:

    D:\Anaconda\lib\site-packages\matplotlib\collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    if self._edgecolors == str('face'):

Might be relevant?

**Comment by joferkington** [comment]
It turns out that all of this is actually because garbage collection works slightly different on Python 3.5.  The `DataCursor` was being garbage collected before `plt.show()` was called.

547730b fixes these issues without a version specific workaround by adding a reference from the each Matplotlib `Figure` used by the data cursor to one or more `DataCursor` instances.  This keeps the `DataCursor` instance alive and prevents it from being garbage collected.

**Comment by pauljmorrison** [comment]
thanks @joferkington ! works like a charm in mpl 1.5.1!

**Comment by anntzer** [comment]
It works, but for some reason I still get the same warning ('method' object is not connected) when closing the figure (which is of course only mildly annoying).

**Comment by joferkington** [comment]
@anntzer - Thanks for letting me know!  For some reason I'm not getting that warning on my 3.5 + qt5 setup, but it's probably due to something I'm overlooking.  I'll look into it a bit more and see if I can get to the bottom of it.  It would be nice to avoid the warning, as well.
